### ISSUE TITLE
marche pas le code me dit que c'est pas un constructeur

### ISSUE THREAD

**Issue by Manaf941** [magichitler/Magic-Hitler-npm-module#1]
wawn

**Comment by Manaf941** [comment]
sa marche pas
ni plus ni moins

**Comment by JacqueSatan** [comment]
Peux-tu me dire où est-ce que l'erreur survient ?

**Comment by Manaf941** [comment]
ah mince j'avais pris ton test qui était `const raid = new MagicHitler({
    client: client,
    prefix: "!"
});`

j'ai regardé tous les docs et j'ai ensuite vu que c'était `const raid = new MagicHitler.Client({
client: client,
prefix: "!" // Optionnel ; Préfixe pour les commandes
});`

juste l'exemple qui est faux

**Comment by Manaf941** [comment]
mais mtn: `raid.spamMessage("@everyone Raid by Magic Hitler", "spam", {
     ^

TypeError: raid.spamMessage is not a function`

**Comment by JacqueSatan** [comment]
En effet, merci pour cette information. Cette erreur-ci est également une erreur de ma présentation, essaye avec raid.spamMessages
